-- RUN FROM SQL EDITOR AS SYSTEM USER

-- CREATE USER
CREATE USER DEV01 PASSWORD Password1;

-- CREATE ROOT PACKAGE FOR USER - USING SQL IS UNSUPPORTED - PERFORM VIA MENUS WHEN POSSIBLE
INSERT INTO _SYS_REPO.PACKAGE_CATALOG(PACKAGE_ID, SRC_SYSTEM, SRC_TENANT, DESCRIPTION, RESPONSIBLE, IS_STRUCTURAL) VALUES ('DEV01','HDB','','DEV01','DEV01',0);

-- GRANT ACCESS TO AFL PAL
GRANT EXECUTE ON SYSTEM.AFL_WRAPPER_GENERATOR TO DEV01;
GRANT EXECUTE ON SYSTEM.AFL_WRAPPER_ERASER TO DEV01;
GRANT AFL__SYS_AFL_AFLPAL_EXECUTE TO DEV01;

-- ENABLE NATIVE DEVELOPMENT ON ROOT PACKAGE & SCHEMA FOR USER VIA REPOSITORY
GRANT EXECUTE ON REPOSITORY_REST TO DEV01;
GRANT REPO.READ, REPO.EDIT_NATIVE_OBJECTS, REPO.ACTIVATE_NATIVE_OBJECTS, REPO.MAINTAIN_NATIVE_PACKAGES, REPO.EDIT_IMPORTED_OBJECTS, REPO.ACTIVATE_IMPORTED_OBJECTS, REPO.MAINTAIN_IMPORTED_PACKAGES ON "DEV01" TO DEV01;
GRANT EXECUTE ON GRANT_ACTIVATED_ROLE TO DEV01;
GRANT EXECUTE ON REVOKE_ACTIVATED_ROLE TO DEV01;

-- AUTHORIZATIONS FOR WEB IDE, DEBUGGING, AND JOB SCHEDULING CONFIGURATION
CALL GRANT_ACTIVATED_ROLE('sap.hana.xs.ide.roles::Developer','DEV01');
CALL GRANT_ACTIVATED_ROLE('sap.hana.xs.ide.roles::TraceViewer','DEV01');
CALL GRANT_ACTIVATED_ROLE('sap.hana.xs.debugger::Debugger','DEV01');
CALL GRANT_ACTIVATED_ROLE('sap.hana.xs.admin.roles::JobAdministrator','DEV01');

-- AUTHORIZATIONS FOR LUMIRA SERVER
/* The following are not working */
CALL GRANT_ACTIVATED_ROLE('sap.bi.common::BI_DATA_ANALYST','DEV01');
CALL GRANT_ACTIVATED_ROLE('sap.bi.common::BI_TECH_USER','DEV01');
--These are working
CALL GRANT_ACTIVATED_ROLE('sap.hana.xs.admin.roles::SQLCCAdministrator','DEV01');
CALL GRANT_ACTIVATED_ROLE('sap.hana.xs.admin.roles::RuntimeConfAdministrator','DEV01');
GRANT MODELING TO DEV01;
