-- RUN FROM SQL EDITOR AS DEV01 USER

-- ENABLE USAGE IN ROLES
GRANT CREATE ANY, DROP, SELECT, INSERT, UPDATE, DELETE, INDEX ON SCHEMA DEV01 TO _SYS_REPO WITH GRANT OPTION;

-- CREATE TWEETS TABLE
CREATE COLUMN TABLE "Tweets" (
	"id" VARCHAR(256) NOT NULL,
	"created" TIMESTAMP,
	"text" NVARCHAR(256),
	"lang" VARCHAR(256),
	"user" VARCHAR(256),
	"replyUser" VARCHAR(256),
	"retweetedUser" VARCHAR(256),
	"lat" DOUBLE,
	"lon" DOUBLE,
	PRIMARY KEY ("id")
);
