-- RUN FROM SQL EDITOR AS DEV01 USER

-- SETUP AFL PAL CLUSTERING

-- CLEANUP
DROP TYPE PAL_T_DATA;
DROP TYPE PAL_T_PARAMS;
DROP TYPE PAL_T_RESULTS;
DROP TYPE PAL_T_CENTERS;
DROP TABLE PAL_SIGNATURE;
CALL SYSTEM.AFL_WRAPPER_ERASER ('DEV01_TweetersClustering');
DROP TABLE PAL_PARAMS;
DROP TABLE PAL_RESULTS;
DROP TABLE PAL_CENTERS;
DROP VIEW "TweetersClusteredSummary";
DROP VIEW "TweetersClustered";

-- CREATE STORED PROCEDURE
CREATE TYPE PAL_T_DATA AS TABLE ("user" VARCHAR(256), "stance" INTEGER, "influence" DOUBLE);
CREATE TYPE PAL_T_PARAMS AS TABLE (NAME VARCHAR(50), INTARGS INTEGER, DOUBLEARGS DOUBLE, STRINGARGS VARCHAR(100));
CREATE TYPE PAL_T_RESULTS AS TABLE ("user" VARCHAR(256), "ClusterNumber" INTEGER, "distance" DOUBLE);
CREATE TYPE PAL_T_CENTERS AS TABLE ("ClusterNumber" INTEGER, "stance" INTEGER, "influence" INTEGER);
CREATE COLUMN TABLE PAL_SIGNATURE (ID INTEGER, TYPENAME VARCHAR(100), DIRECTION VARCHAR(100));
INSERT INTO PAL_SIGNATURE VALUES (1, 'DEV01.PAL_T_DATA', 'in');
INSERT INTO PAL_SIGNATURE VALUES (2, 'DEV01.PAL_T_PARAMS', 'in');
INSERT INTO PAL_SIGNATURE VALUES (3, 'DEV01.PAL_T_RESULTS', 'out');
INSERT INTO PAL_SIGNATURE VALUES (4, 'DEV01.PAL_T_CENTERS', 'out');
GRANT SELECT ON PAL_SIGNATURE TO SYSTEM;
CALL SYSTEM.AFL_WRAPPER_GENERATOR ('DEV01_TweetersClustering', 'AFLPAL', 'KMEANS', PAL_SIGNATURE);

-- CREATE PARAMETER TABLE
CREATE COLUMN TABLE PAL_PARAMS LIKE PAL_T_PARAMS;
INSERT INTO PAL_PARAMS VALUES ('THREAD_NUMBER', 2, null, null);
--INSERT INTO PAL_PARAMS VALUES ('GROUP_NUMBER', 3, null, null);
INSERT INTO PAL_PARAMS VALUES ('GROUP_NUMBER_MIN', 5, null, null);
INSERT INTO PAL_PARAMS VALUES ('GROUP_NUMBER_MAX', 10, null, null);
INSERT INTO PAL_PARAMS VALUES ('INIT_TYPE', 4, null, null);
INSERT INTO PAL_PARAMS VALUES ('DISTANCE_LEVEL', 2, null, null);
INSERT INTO PAL_PARAMS VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO PAL_PARAMS VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO PAL_PARAMS VALUES ('NORMALIZATION', 0, null, null);

-- CREATE OUTPUT TABLES
CREATE COLUMN TABLE PAL_RESULTS LIKE PAL_T_RESULTS;
CREATE COLUMN TABLE PAL_CENTERS LIKE PAL_T_CENTERS;

-- CREATE VIEWS FOR ODATA
CREATE VIEW "TweetersClustered" AS
	SELECT s.*, c."ClusterNumber" + 1 AS "ClusterNumber"
	 FROM "Tweeters" s
	 INNER JOIN "PAL_RESULTS" c ON c."user" = s."user"
	 ;
CREATE VIEW "TweetersClusteredSummary" AS
	SELECT "ClusterNumber", c."stance", c."influence", COUNT(*) AS "users"
	 FROM "Tweeters" t
	 INNER JOIN "TweetersClustered" c ON c."user" = t."user"
	 GROUP BY "ClusterNumber", c."stance", c."influence"
	 ;

-- RUNTIME
TRUNCATE TABLE PAL_RESULTS;
TRUNCATE TABLE PAL_CENTERS;
CALL _SYS_AFL."DEV01_TweetersClustering"("Tweeters", PAL_PARAMS, PAL_RESULTS, PAL_CENTERS) with overview;

-- TESTING
SELECT * FROM "$TA_tweets";
SELECT * FROM "Tweeters";
SELECT * FROM "TweetersClustered";
SELECT * FROM "TweetersClusteredSummary";
SELECT "ClusterNumber", COUNT(*) AS "Users" FROM "TweetersClustered" GROUP BY "ClusterNumber" ORDER BY "ClusterNumber";
