-- RUN FROM SQL EDITOR AS DEV01 USER

-- CREATE SETTINGS TABLE
CREATE COLUMN TABLE "Settings" (
	"name" VARCHAR(256) NOT NULL,
	"value" VARCHAR(1024),
	PRIMARY KEY ("name")
);
INSERT INTO "Settings" VALUES ('TRACK','#whatever');
